version: "2"
services:
    www:
        build: .
        ports:
            - "8080:80"
        links:
            - db
        networks:
            - default
        hostname: lab.feifei.tw
    db:
        image: mysql:5.7.13
        ports:
            - "8081:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        networks:
            - default
        hostname: lab.feifei.tw
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8082:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        hostname: lab.feifei.tw
    web2:
        build:
            context: .
            dockerfile: Dockerfile.web2
        ports:
            - "8083:80"
        hostname: rcelab.feifei.tw
    web3:
        build:
            context: .
            dockerfile: Dockerfile.web3
        ports:
            - "8084:80"
        hostname: ctflab.feifei.tw
    exam:
        build:
            context: .
            dockerfile: Dockerfile.exam
        ports:
            - "8085:80"
        hostname: exam.feifei.tw
